version: "3"

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    command:
      ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
    volumes:
      - ./mariadb_data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mobiledev
      MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    command: ["bash", "-c", "./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000"]
    container_name: django
    restart: always
    volumes:
      - ./api:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db